title: "Use OCI DevOps CICD with Functions"
description: "Create Function and DevOps Deploy service to manage your Functions deployments."
schemaVersion: 0.0.0
version: "20211123"
locale: "en"

#################
# Variable Groups
#################

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - user_ocid
  - fingerprint
  - private_key_path
  - network_cidrs
  - app_version
  - app_version2
  - deploy_pipeline_deploy_pipeline_parameters_items_default_value
  - deploy_pipeline_deploy_pipeline_parameters_items_description
  - deploy_pipeline_deploy_pipeline_parameters_items_name
  - compartment_ocid
  - release

- title: Required Configuration
  visible: true  
  variables:
  - app_name
  - ocir_user_name
  - ocir_user_password
  - execute_deployment
  - show_advanced

- title: DevOps Project
  visible: true  
  variables:
  - compartment_id
  - project_description
  - project_logging_config_is_archiving_enabled
  - project_logging_config_display_name_prefix
  - project_logging_config_retention_period_in_days

- title: Function & Network Configuration 
  visible: true  
  variables:
  - VCN-CIDR
  - fnsubnet-CIDR
  - ocir_repo_name

- title: DevOps Environments
  visible: 
      and:
        - show_advanced
  variables:
  - environment_type 

- title: DevOps Artifacts
  visible: 
      and:
        - show_advanced
  variables:
  - deploy_artifact_source_type
  - deploy_artifact_type
  - argument_substitution_mode

- title: Pipelines & Stages
  visible: 
      and:
        - show_advanced  
  variables:
  - deploy_stage_deploy_stage_type
  - deploy_stage_namespace

- title: Policy Settings
  description: Policy setting for the stack deployment
  visible: true  
  variables:
  - create_dynamic_group_for_devops_pipln_in_compartment
  - create_dynamic_group_for_nodes_in_compartment
  - existent_dynamic_group_for_nodes_in_compartment
  - create_compartment_policies
  - create_tenancy_policies
    

######################
# Variable Definitions
######################

variables:

  compartment_id: 
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create resources"
    required: true

  app_name:
    type: string
    title: "HelloWorldFn"
    required: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options, allowing enable customer-managed encryption keys, select your ssh key, select/unselect cluster utilities, do not create policies, and other advanced options"
    visible: true
    default: false

  execute_deployment:
    type: boolean
    title: "Execute deployment in DevOps Pipeline?"
    description: "Choose if you want to start deployment in DevOps Pipeline as a part of this Terraform automation."
    visible: true
    default: false

## Function

  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "VCN CIDR block where you want to create the App/Function resources."
  
  fnsubnet-CIDR:
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "Subnet CIDR block where you want to create the App/Function resources."
  
  ocir_repo_name:
    type: string
    required: true
    visibile: true
    title: "OCIR repository name"
    description: "Oracle Cloud Infrastructure Registry repository name (for example functions)"
  
  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

  ocir_user_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 


## DevOps

  project_description:
    type: string
    title: "Project description"
    description: "Choose DevOps Project description"
    default: "DevOps Project for Function deployment"
    required: false    

  project_logging_config_is_archiving_enabled:
    type: boolean
    title: "Archiving enabled for Project Logging"
    description: "Archiving enabled for Project Logging"
    default: false
    required: true
    visible: 
      and:
        - show_advanced

  project_logging_config_display_name_prefix:
    type: string
    title: "Prefix for Logging Config"
    description: "Prefix for Logging Config"
    default: "fn-"
    required: true
    visible: 
      and:
        - show_advanced

  project_logging_config_retention_period_in_days:
    type: number
    title: "Project Logs retention period"
    description: "Days to retain logs from the Project."
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 30
    required: true
    visible: 
      and:
        - show_advanced
  
  #############
  # Environment
  ############# 

  environment_type:
    type: enum
    enum:
      - "FUNCTION"
    title: "Environment Type"
    description: "The type of environment to target. Stack currently supports only FUNCTION"
    default: "FUNCTION"
    visible: 
      and:
        - show_advanced

  ############
  # Artifacts
  ############
  deploy_artifact_source_type:
    type: enum
    enum:
      - "OCIR"
    title: "Artifact Source Type"
    description: "The source type of artifact. Stack currently supports only OCIR"
    default: "OCIR"

  deploy_artifact_type:
    type: enum
    enum:
      - "DOCKER_IMAGE"
    title: "Artifact Type"
    description: "The type of Artifact. Stack currently supports only DOCKER_IMAGE"
    default: "DOCKER_IMAGE"

  argument_substitution_mode:
    type: enum
    enum:
      - "NONE"
    title: "Argument substitution for the Artifact"
    description: "Artifacts can have arguments that are substituted with values are runtime. Stack currently supports only NONE"
    default: "NONE"
  
  ###########
  # Pipeline
  ###########
  create_dynamic_group_for_devops_pipln_in_compartment:
    type: boolean
    title: "Create a Dynamic Group for DevOps Pipelines"
    description: "You need to be an administrator to do this. Alternatively you can have the administrator create Dynamic group for you." 
    default: true

  deploy_stage_deploy_stage_type:
    type: enum
    enum:
      - "DEPLOY_FUNCTION"
    title: "Stage Type"
    description: "DevOps Stage Type"
    default: "DEPLOY_FUNCTION"

  deploy_stage_namespace:
    type: string
    title: "Namespace to use"
    description: "namespace to use for deployment."
    default: "default"
  
  create_dynamic_group_for_nodes_in_compartment:
    type: boolean
    title: "Create Dynamic Group for Worker Nodes in the Compartment"
    required: true
    visible:
      and:
        - show_advanced

  existent_dynamic_group_for_nodes_in_compartment:
    type: string
    required: true
    title: "Existent Dynamic Group"
    visible:
      and:
        - and:
          - show_advanced
        - or:
          - create_compartment_policies
          - create_tenancy_policies
        - not:
          - create_dynamic_group_for_nodes_in_compartment
        
  create_compartment_policies:
    type: boolean
    title: "Create Compartment Policies"
    required: true
    visible:
      and:
        - show_advanced

  create_tenancy_policies:
    type: boolean
    title: "Create Tenancy Policies"
    required: true
    visible:
      and:
        - show_advanced
  
  
 
